# Generated by Django 4.2.5 on 2023-09-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_food_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='original_price',
        ),
    ]
