# Generated by Django 4.2.5 on 2023-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0004_alter_food_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='last_updated',
            field=models.DateTimeField(help_text='登録日'),
        ),
    ]
