# Generated by Django 4.2.5 on 2023-09-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0005_alter_food_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarket',
            name='supermarket_id',
        ),
    ]
